version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        - PHP_EXTENSIONS=pdo_pgsql
    networks:
      - internal
  postgres-db:
    container_name: localhost
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    command: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

      PGUSER: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
networks:
  internal:
    driver: bridge